oldLighting=true
vignette=true

uniform.float.framemod8 = frameCounter % 8

screen=<empty> <empty> BY TYPE_AA <empty> <empty> [LT] [PP] [OL]

screen.LT=<empty> <empty> shadowDistance shadowMapResolution FOG ENABLE_SKY ENABLE_SHADOWS
screen.PP=<empty> <empty> MOTION_BLUR MOTION_BLURRING_STRENGTH
screen.OL=<empty> <empty> ENABLE_OUTLINE OUTLINE_COLOR_R OUTLINE_COLOR_G OUTLINE_COLOR_B OUTLINE_STRENGTH OUTLINE_RADIUS

sliders=shadowDistance shadowMapResolution MOTION_BLURRING_STRENGTH